### PR TITLE
torchvision 0.12.0

### PR DESCRIPTION
**Pull request by h-vetinari**
The update bot choked on something, and indeed, my local attempts to rerender hang indefinitely, even though I tried a couple tweaks in an attempt at mitigation.

Closes #51

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Fails with a pytorch-related import:
```
  File "`[...]/lib/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py", line 5, in <module>
    from torch.ao.quantization import QuantStub, DeQuantStub
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' 
``

**Comment by hmaarrfk** [comment]
This likely needs pytorch 1.11.0

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Rebased on #49, WIP until that one is merged

**Comment by h-vetinari** [comment]
AFAICT, _all_ the errors are due to not raising an error upon use of what's supposed to be a private implementation:
```
        if "16" in img_path:
            # 16 bits image decoding is supported, but only as a private API
            # FIXME: see https://github.com/pytorch/vision/issues/4731 for potential solutions to making it public
>           with pytest.raises(RuntimeError, match="At most 8-bit PNG images are supported"):
E           Failed: DID NOT RAISE <class 'RuntimeError'>
```

**Comment by hmaarrfk** [comment]
Thanks for reaching out upstream. Curious they didn't hit the bug.

**Comment by h-vetinari** [comment]
Well, unless you put a hash in the path, it's not that likely. In our case though, since `torchvision-split_1647862604097` seems to be using an unix epoch integer, we're _guaranteed_ to hit it, as it's in the two most significant bits...
```
>>> pd.Series([pd.Timestamp.now()]).astype(np.int64)[0] // 10 ** 6
1647903504531
```

**Comment by hmaarrfk** [comment]
I guess we need to wait 2000 years to release it! 🤣

**Comment by h-vetinari** [comment]
@conda-forge/torchvision
This is ready, PTAL. Since there are no controversial changes (to my mind) I'll probably merge in 10-12h if there are no comments.

**Review by hmaarrfk — APPROVED** [review]

**Pull request merged**
