### PR TITLE
Bump to 0.15.1 + pytorch 2.0

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #63 
Closes #72

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Needs the migrator to pytorch 2.0.0

**Comment by h-vetinari** [comment]
@Tobias-Fischer @hmaarrfk @ngam
This is now passing for the cpu builds, but runs into some (trivial-looking) tolerance violation for the cuda build (4 failures)
```
FAILED test/test_transforms_v2_functional.py::TestKernels::test_batched_vs_single[cpu-gaussian_blur_video-{03,06,21,24}]
```

All have identical-looking errors à la:
```
Mismatched elements: 1 / 3465 (0.0%)
Greatest absolute difference: 1 at index (0, 0, 2, 10)
Greatest relative difference: 0.006666666828095913 at index (0, 0, 2, 10)

The failure occurred for item [3]
Failure happened for the following parameters:

tensor(shape=[4, 5, 3, 7, 33], dtype=torch.uint8, device=cpu)
kernel_size=[3, 3]
```

For context, this isn't tragic IMO:
```
= 4 failed, 72995 passed, 73447 skipped, 1066 deselected, 1629 xfailed, 4404 warnings in 818.68s (0:13:38) =
```

I guess the easiest might be to skip those.

**Comment by Tobias-Fischer** [comment]
Happy to skip these tests ..

**Comment by h-vetinari** [comment]
> Is this error big or not? It's pretty suspicious that 1) all failures are the exact same and 2) the value of 1.

That's because all values are integers and exactly one entry out of the whole tensor is off by the smallest possible difference, 1.

**Comment by h-vetinari** [comment]
> Okay, an actual error of 1 is pretty big imo

It's the smallest possible error for the data type, so I think it wouldn't be a big deal. That said, yes, we should solve it, hence why I wanted to get people's opinions.

What's weird to me is that it only appears on the cuda builds

**Comment by hmaarrfk** [comment]
We could upload build artifacts and test more carefully if you All want, but i have a hunch it is likely ok...

**Comment by weiji14** [comment]
The gaussian blur tests are known to be flaky due to some non-determinism on CUDA (see https://github.com/pytorch/vision/pull/6755), though that should have been fixed in https://github.com/pytorch/vision/pull/6762. Perhaps the flakiness has resurfaced again? I also think it sholud be fine to skip the tests and merge this PR first.

**Comment by Tobias-Fischer** [comment]
This is ready for review @conda-forge/torchvision

**Review by h-vetinari — APPROVED** [review]

**Comment by hmaarrfk** [comment]
perfect!

**Pull request merged**
