### PR TITLE
testing up to v0.11.1

### PR DESCRIPTION
**Pull request by ngam**
Just testing here separately from the main pr. 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
I'm confused since it is having a hard time importing av but it is a pretty standard recipe

https://github.com/conda-forge/av-feedstock

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
giving up on this...

**Pull request closed without merging**
