### PR TITLE
BUG: Update dep pinnings

### LINKED ISSUE #79: CUDA minor version mismatch error between pytorch and torchvision possible
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Since pytorch is now build against CUDA 11.8, torchvision is only built against CUDA 11.2, and torchvision does not pin the cuda version to the minor CUDA version, the following runtime error is possible.

```
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.8 and torchvision has CUDA Version=11.2. Please reinstall the torchvision that matches your PyTorch install.
```

Since apparently torchvision cares which whether the CUDA version used to compile pytorch matches down to the minor version, this package should be pinning the `cuda-version` package down to the minor version. I believe the CUDA compiler packages only exporrt pins to the major version; this is why you can install a torchvision compiled with CUDA 11.2 in a CUDA 11.8 environment.

### Installed packages

```shell
torchvision=0.15
pytorch-gpu
cuda-version=11
```

### Environment info

```shell
active environment : base
    active env location : /home/beams/DCHING/miniconda3
            shell level : 1
       user config file : /home/beams/DCHING/.condarc
 populated config files : /home/beams/DCHING/miniconda3/.condarc
                          /home/beams/DCHING/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=broadwell
                          __cuda=11.2=0
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /home/beams/DCHING/miniconda3  (writable)
      conda av data dir : /home/beams/DCHING/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/beams/DCHING/miniconda3/pkgs
                          /home/beams/DCHING/.conda/pkgs
       envs directories : /home/beams/DCHING/miniconda3/envs
                          /home/beams/DCHING/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Linux/4.18.0-240.el8.x86_64 rhel/8.4 glibc/2.28 solver/libmamba conda-libmamba-solver/23.3.0 libmambapy/1.4.2
                UID:GID : 1992:3234
             netrc file : /home/beams/DCHING/.netrc
           offline mode : False
```

### PR DESCRIPTION
**Pull request by carterbox**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #79
Partial #22 

The purpose of this PR is to update the pytorch pinnings to match upstream according to their stated compatability matrix and according to their runtime checks.

I did this by

1. Manually setting the pytorch version instead of trying to capture the channel-wide pinnings, so that this package is always uses the version of pytorch declared by upstream as compatible.
2. Including the CUDA version in the build string pinning because torchvision checks that the pytorch library was compiled with the same minor version of CUDA.

As a bonus, I also:
1. Added site packages to the rpath to supress linker warnings
2. Added missing pip args `--no-deps --no-build-isolation` which are not automatically added by us when pip is called from a script in the outputs section instead of from a build script in the top-level package.
3. Skipped a test broken by a new version of pillow

### CODE REVIEW

**Comment by carterbox** [comment]
Not sure why we're trying to run almost all of the unit tests, but these tests are failing on [test_draw_boxes](https://github.com/pytorch/vision/blob/15c166ac127db5c8d1541b3485ef5730d34bb68a/test/test_utils.py#L95).

[Upstream has identified the issue](https://github.com/pytorch/vision/issues/8051) as something caused by a change with pillow 10.1.0, so it is unrelated to this PR. They fixed the test by updating the reference image in a later release, so it's fine that this test fails. I think the best approach would be to skip that test because it doesn't indicate a problem for downstream users.

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
> Not sure why we're trying to run almost all of the unit tests

Because just import tests or small test scripts are woefully inadequate for testing whether a given package is fully functional. I think it should be our standard everywhere (modulo timeout/resource issues).

PS. Thanks for tackling this! 🙏

**Comment by hmaarrfk** [comment]
> Because just import tests or small test scripts are woefully inadequate for testing whether a given package is fully functional. I think it should be our standard everywhere (modulo timeout/resource issues).

yeah... but it adds 10MB to the package..... so its less than idea IMO.

**Comment by hmaarrfk** [comment]
Thank you!

**Comment by h-vetinari** [comment]
> but it adds 10MB to the package..... so its less than idea IMO.

So let's split off the tests into a separate output - best of both worlds (except that you don't like multi output recipes 😜)

**Comment by hmaarrfk** [comment]
lol, that is a true statement ....

**Pull request merged**
