### PR TITLE
Pin correctly

### PR DESCRIPTION
**Pull request by hmaarrfk**
It seems that the files have not been pinned correctly. I'm trying to understand how to tell others to pin. This is an easy recipe to test on. 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I think this is pinning things correctly now.

The pin on runtime pytorch is now:

image

In the index.json.

If somebody else from @conda-forge/torchvision wants to review, just to triple check that would be greatly appreciated.
[torchvision-0.11.2-cuda112py39h14c6492_3.zip](https://github.com/conda-forge/torchvision-feedstock/files/7964914/torchvision-0.11.2-cuda112py39h14c6492_3.zip)  <- The tar.bz2 file is in the zip

**Comment by mikemhenry** [comment]
How does this work:
`pytorch {{ pytorch }} {{ torch_proc_type }}` 

without a `conda_build_config.yaml` listing `pytorch` and `torch_proc_type` variants?

**Comment by hmaarrfk** [comment]
Right

**Comment by mikemhenry** [comment]
https://github.com/conda-forge/pytorch_cluster-feedstock/pull/26

How did you generate the `.ci_support/migrations` with `pytorch` in them? In the above PR, I just used a `conda_build_config.yaml`

**Comment by hmaarrfk** [comment]
The migrator typically creates it for you, but you can copy it over yourself too

**Pull request merged**
