### PR TITLE
Rebuild to pick up correct pytorch run_export

### LINKED ISSUE #47: Segmentation fault and PyTorch compatibility
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

If I run `conda install torchvision`, it currently installs PyTorch 1.11.0 (the latest version) and torchvision 0.11.0 (the previous version). These versions are incompatible, and lead to a segmentation fault during import:
```console
$ python -X faulthandler
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
Fatal Python error: Segmentation fault

Current thread 0x00007fcfb6999740 (most recent call first):
  File "/anaconda/envs/adam/lib/python3.9/ctypes/__init__.py", line 374 in __init__
  File "/anaconda/envs/adam/lib/python3.9/site-packages/torch/_ops.py", line 220 in load_library
  File "/anaconda/envs/adam/lib/python3.9/site-packages/torchvision/extension.py", line 85 in _load_library
  File "/anaconda/envs/adam/lib/python3.9/site-packages/torchvision/io/image.py", line 9 in <module>
...
  File "<stdin>", line 1 in <module>
Segmentation fault (core dumped)
```
This is due to a number of missing symbols in the following libraries:
```console
$ ldd -r /anaconda/envs/adam/lib/python3.9/site-packages/torchvision/image.so
...
undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE	(/anaconda/envs/adam/lib/python3.9/site-packages/torchvision/image.so)
undefined symbol: _ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_	(/anaconda/envs/adam/lib/python3.9/site-packages/torchvision/image.so)
undefined symbol: _ZN3c1017RegisterOperatorsD1Ev	(/anaconda/envs/adam/lib/python3.9/site-packages/torchvision/image.so)
$ ldd -r /anaconda/envs/adam/lib/python3.9/site-packages/torchvision/_C.so 
...
undefined symbol: _ZTIN5torch8autograd4NodeE	(/anaconda/envs/adam/lib/python3.9/site-packages/torchvision/_C.so)
undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev	(/anaconda/envs/adam/lib/python3.9/site-packages/torchvision/_C.so)
undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev	(/anaconda/envs/adam/lib/python3.9/site-packages/torchvision/_C.so)
```
Shouldn't the PyTorch dependency version be pinned according to [this table](https://github.com/pytorch/vision#installation)?

### Installed packages

```shell
# packages in environment at /anaconda/envs/adam:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
absl-py                   1.0.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
affine                    2.3.0                      py_0    conda-forge
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
anyio                     3.5.0                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.10.0                   pypi_0    pypi
black                     22.1.0                   pypi_0    pypi
bleach                    4.1.0                    pypi_0    pypi
blosc                     1.21.0               h9c3ff4c_0    conda-forge
boost-cpp                 1.74.0               h6cacc03_7    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.0.0                    pypi_0    pypi
cairo                     1.16.0            ha12eb4b_1010    conda-forge
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
cfitsio                   4.0.0                h9a35b8e_0    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.0.4            py39hf3d152e_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
colorama                  0.4.4                    pypi_0    pypi
coverage                  6.3.2                    pypi_0    pypi
cudatoolkit               11.6.0              habf752d_10    conda-forge
curl                      7.82.0               h2283fc2_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.28          py39he80948d_0    conda-forge
debugpy                   1.5.1                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
efficientnet-pytorch      0.6.3                    pypi_0    pypi
einops                    0.4.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                      pypi_0    pypi
executing                 0.8.3                    pypi_0    pypi
expat                     2.4.7                h27087fc_0    conda-forge
ffmpeg                    4.3.2                h37c90e5_3    conda-forge
fiona                     1.8.21           py39hc5a795b_0    conda-forge
flake8                    4.0.1                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.96              h8e229c2_2    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.31.1           py39hb9d737c_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.6                h7f98852_0    conda-forge
frozenlist                1.3.0                    pypi_0    pypi
fsspec                    2022.2.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gdal                      3.4.2            py39h85832e7_0    conda-forge
geos                      3.10.2               h9c3ff4c_0    conda-forge
geotiff                   1.7.1                h509b78c_0    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.6.2                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.44.0                   pypi_0    pypi
h5py                      3.6.0           nompi_py39h7e08c79_100    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h4df4325_104    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                      pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
importlib-metadata        4.11.3                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 6.9.2                    pypi_0    pypi
ipython                   8.1.1                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.0                    pypi_0    pypi
isort                     5.10.1                   pypi_0    pypi
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h7f98852_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
json5                     0.9.6                    pypi_0    pypi
jsonschema                4.4.0                    pypi_0    pypi
jupyter-client            7.1.2                    pypi_0    pypi
jupyter-core              4.9.2                    pypi_0    pypi
jupyter-packaging         0.11.1                   pypi_0    pypi
jupyter-server            1.15.6                   pypi_0    pypi
jupyterlab                3.3.2                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-server         2.11.2                   pypi_0    pypi
jupyterlab-widgets        1.1.0                    pypi_0    pypi
kealib                    1.4.14               h87e4c3c_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.0            py39hf939315_0    conda-forge
kornia                    0.6.3                    pypi_0    pypi
krb5                      1.19.3               h08a2579_0    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
laspy                     2.1.2                    pypi_0    pypi
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0            13_linux64_mkl    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0            13_linux64_mkl    conda-forge
libcurl                   7.82.0               h2283fc2_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgdal                   3.4.2                hda961b2_0    conda-forge
libgfortran-ng            11.2.0              h69a702a_14    conda-forge
libgfortran5              11.2.0              h5c6108e_14    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0            13_linux64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.2                 h676c864_0    conda-forge
libprotobuf               3.19.4               h780b84a_0    conda-forge
librttopo                 1.1.0                hf69c175_9    conda-forge
libspatialite             5.0.1               ha867d66_15    conda-forge
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzip                    1.8.0                h1c5bbd1_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvm-openmp               13.0.1               he0ac6c6_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.3.6                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib-base           3.5.1            py39h2fa2bec_0    conda-forge
matplotlib-inline         0.1.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2022.0.1           h8d4b97c_803    conda-forge
multidict                 6.0.2                    pypi_0    pypi
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy                      0.941                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
nbclassic                 0.3.7                    pypi_0    pypi
nbclient                  0.5.13                   pypi_0    pypi
nbconvert                 6.4.4                    pypi_0    pypi
nbformat                  5.2.0                    pypi_0    pypi
nbmake                    1.3.0                    pypi_0    pypi
nbsphinx                  0.8.8                    pypi_0    pypi
ncurses                   6.3                  h9c3ff4c_0    conda-forge
nest-asyncio              1.5.4                    pypi_0    pypi
nettle                    3.6                  he412f7d_0    conda-forge
ninja                     1.10.2               h4bd325d_1    conda-forge
notebook                  6.4.10                   pypi_0    pypi
notebook-shim             0.1.0                    pypi_0    pypi
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.74                 hb5efdd6_0    conda-forge
numpy                     1.22.3           py39h18676bf_0    conda-forge
oauthlib                  3.2.0                    pypi_0    pypi
omegaconf                 2.1.1                    pypi_0    pypi
open3d                    0.15.2                   pypi_0    pypi
opencv-python             4.5.5.64                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.9.0                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1            py39hae2aec6_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platformdirs              2.5.1                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
poppler                   22.01.0              h1434ded_1    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.2                 hce44dc1_0    conda-forge
pretrainedmodels          0.7.4                    pypi_0    pypi
proj                      9.0.0                h93bde94_1    conda-forge
prometheus-client         0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.28                   pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0.4            py39hce5d2b2_0    conda-forge
pycodestyle               2.8.0                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.9.0                    pypi_0    pypi
pydeprecate               0.3.1                    pypi_0    pypi
pydocstyle                6.1.1                    pypi_0    pypi
pyflakes                  2.4.0                    pypi_0    pypi
pygments                  2.11.2                   pypi_0    pypi
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.0            py39hcadae2f_2    conda-forge
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pystac                    1.4.0                    pypi_0    pypi
pytest                    7.1.1                    pypi_0    pypi
pytest-cov                3.0.0                    pypi_0    pypi
python                    3.9.10          hc74c709_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.11.0          cpu_py39h7613f69_0    conda-forge
pytorch-lightning         1.5.10                   pypi_0    pypi
pytorch-sphinx-theme      0.0.24                   pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
radiant-mlhub             0.4.1                    pypi_0    pypi
rarfile                   4.0                pyh9f0ad1d_0    conda-forge
rasterio                  1.2.10           py39h2e4b6e6_5    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
rtree                     0.9.7                    pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.8.0                    pypi_0    pypi
segmentation-models-pytorch 0.2.1                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                59.5.0                   pypi_0    pypi
shapely                   1.8.0            py39ha65c37e_5    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
sniffio                   1.2.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
snuggs                    1.4.7                      py_0    conda-forge
soupsieve                 2.3.1                    pypi_0    pypi
sphinx                    4.4.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.37.1               h4ff8645_0    conda-forge
stack-data                0.2.0                    pypi_0    pypi
tbb                       2021.5.0             h4bd325d_0    conda-forge
tensorboard               2.8.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
terminado                 0.13.3                   pypi_0    pypi
testpath                  0.6.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tiledb                    2.7.1                h3f4058f_0    conda-forge
timm                      0.4.12                   pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.10.0                   pypi_0    pypi
torchmetrics              0.7.2                    pypi_0    pypi
torchvision               0.11.3          cpu_py39h5f8393d_1    conda-forge
tornado                   6.1                      pypi_0    pypi
tqdm                      4.63.0                   pypi_0    pypi
traitlets                 5.1.1                    pypi_0    pypi
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzcode                    2022a                h166bdaf_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py39h3811e60_0    conda-forge
urllib3                   1.26.9                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.3.1                    pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.0                    pypi_0    pypi
x264                      1!161.3030           h7f98852_1    conda-forge
xerces-c                  3.2.3                h8ce2273_4    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yarl                      1.7.2                    pypi_0    pypi
zipfile-deflate64         0.2.0                    pypi_0    pypi
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

### Environment info

```shell
active environment : adam
    active env location : /anaconda/envs/adam
            shell level : 2
       user config file : /home/adam/.condarc
 populated config files : 
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /anaconda  (writable)
      conda av data dir : /anaconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /anaconda/pkgs
                          /home/adam/.conda/pkgs
       envs directories : /anaconda/envs
                          /home/adam/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.5 Linux/5.4.0-1069-azure ubuntu/18.04.5 glibc/2.27
                UID:GID : 1002:1003
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by h-vetinari**
Closes #47

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
What the hell...? 3 different failures in 5 different builds:
* all CUDA 11.1 builds:
  ```
  import: 'torchvision'
  terminate called after throwing an instance of 'std::bad_alloc'
    what():  std::bad_alloc
  ```
* CUDA 11.0 with (only!) python 3.8:
  ```
  [...]
  test/test_io.py::TestVideo::test_read_video_timestamps_corrupted_file PASSED [ 89%]
  test/test_io.py::TestVideo::test_read_video_partially_corrupted_file SKIPPED [ 89%]
  Fatal Python error: Segmentation fault

  Thread 0x00007f228d2f5700 (most recent call first):
  <no Python frame>

  Current thread 0x00007f235823d740 (most recent call first):
    File "/home/conda/feedstock_root/build_artifacts/torchvision-split_1647829120678/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/site-packages/torchvision/io/video.py", line 124 in write_video
    File "/home/conda/feedstock_root/build_artifacts/torchvision-split_1647829120678/test_tmp/test/test_io.py", line 263 in test_write_video_with_audio
  ```
* osx-64 with (only!) python 3.9:
  ```
  import: 'torchvision'
  libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector
  ```

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
was it the pinnings or the compilers?

**Comment by h-vetinari** [comment]
> was it the pinnings or the compilers?

IMO can't be the pinning as we were building with 1.10 before already, just not adding the right run-export.

**Comment by hmaarrfk** [comment]
Yeah, so that particular one that the downloaded, was built with build 0. which didn't have the run export.

**Comment by hmaarrfk** [comment]
At least now the test section will fail to import if it doesn't pick it up.

I've also attempted to do something like

```
- pytorch 1.10 *_1  # [pytorch == '1.10']
```
To ensure that build 1 gets selected

**Comment by h-vetinari** [comment]
Good catch with https://github.com/conda-forge/torchvision-feedstock/pull/48/commits/7ce31dd6891855f2854a6f85b9c864deb3b63811. I checked the logs again and 2/3 cases did pull in pytorch 1.11. However, the CUDA 11.0 failure was with pytorch 1.10

**Comment by h-vetinari** [comment]
Let me back out the compiler downgrade then (I'll keep your commit)

**Comment by h-vetinari** [comment]
I have a fix for the failure but want to let CI finish first to see if any other problems still crop up.

**Comment by hmaarrfk** [comment]
build 0s got pick up during the two build that failed. maybe we should just mark them as broken....

**Comment by h-vetinari** [comment]
> build 0s got pick up during the two build that failed. maybe we should just mark them as broken....

I've got this lined up:
```diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index ded04d6..6a919bc 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -52,7 +52,10 @@ outputs:
         - numpy
         # exclude 8.3.0 and 8.3.1 specifically due to pytorch/vision#4146, python-pillow/Pillow#5571
         - pillow >=5.3.0,!=8.3.0,!=8.3.1
-        - pytorch
+        # TODO: revert this; temporary hack to force
+        # solver to pick build with correct run-export
+        - pytorch =1.10.2=*_1
+        # - pytorch
         - pytorch =*={{ torch_proc_type }}*
       run:
         - python
```

**Comment by hmaarrfk** [comment]
Sure. Why not

**Comment by h-vetinari** [comment]
I managed to restart the failures before the automerge picked up the failure - one is gone and one reappeared. But I'm going to merge this now anyway.

**Comment by h-vetinari** [comment]
Merging was the right decision; the failure seems to circle through the builds (original failure on main was yet another build), and restarting fixed it.

**Pull request merged**
