### PR TITLE
update pytorch pin

### PR DESCRIPTION
**Pull request by ngam**
No hurry on this, just a cosmetic update of the pin to make sure we are moving all the pieces in sync. 

Currently, install torchivison 0.11.2 will force you to downgrade pytorch to 1.10.0.

### CODE REVIEW

**Comment by ngam** [comment]
@hmaarrfk no idea why this very particular case is failing for only one of the many variants:

```
___________________ TestNMS.test_batched_nms_implementations ___________________

self = <test_ops.TestNMS object at 0x7fc89ec99250>

    def test_batched_nms_implementations(self):
        """Make sure that both implementations of batched_nms yield identical results"""
    
        num_boxes = 1000
        iou_threshold = .9
    
        boxes = torch.cat((torch.rand(num_boxes, 2), torch.rand(num_boxes, 2) + 10), dim=1)
        assert max(boxes[:, 0]) < min(boxes[:, 2])  # x1 < x2
        assert max(boxes[:, 1]) < min(boxes[:, 3])  # y1 < y2
    
        scores = torch.rand(num_boxes)
        idxs = torch.randint(0, 4, size=(num_boxes,))
        keep_vanilla = ops.boxes._batched_nms_vanilla(boxes, scores, idxs, iou_threshold)
        keep_trick = ops.boxes._batched_nms_coordinate_trick(boxes, scores, idxs, iou_threshold)
    
        torch.testing.assert_close(
>           keep_vanilla, keep_trick, msg="The vanilla and the trick implementation yield different nms outputs."
        )
E       AssertionError: The values for attribute 'shape' do not match: torch.Size([42]) != torch.Size([43]).

```

**Comment by hmaarrfk** [comment]
sorry, we had the wrong pin in pytorch 1.10.0 pinnign to patch version. we hould update the migrator to utilize 1.10.1 or do a repo patch.

**Comment by ngam** [comment]
> sorry, we had the wrong pin in pytorch 1.10.0 pinnign to patch version. we hould update the migrator to utilize 1.10.1 or do a repo patch.

No, I don't think anything serious is necessary here. As you correctly pointed out, the difference should be minor and compatibility should be okay. I just wanted to make note of that for us to fix it at some point. Nothing immediate.

**Comment by hmaarrfk** [comment]
it will be fixed once this latest build is out. I'll try to write a repo patch soon.

**Comment by ngam** [comment]
Looking at this https://anaconda.org/conda-forge/torchvision/files
depends | __glibc >=2.17, __glibc >=2.17,<3.0.a0, cudatoolkit >=11.2,<12, cudnn >=8.2.1.32,<9.0a0, ffmpeg >=4.3.2,<5.0a0, jpeg >=9e,<10a, libgcc-ng >=9.4.0, libpng >=1.6.37,<1.7.0a0, libstdcxx-ng >=9.4.0, numpy >=1.18.5,<2.0a0, pillow >=5.3.0,!=8.3.0,!=8.3.1, python >=3.7,<3.8.0a0, python_abi 3.7.* *_cp37m, pytorch * cuda*

so I am confused about the way you're pinning currently and how you're addressing the ffmpeg stuff. This doesn't seem like the intended solution?

**Comment by ngam** [comment]
In particular:
- ffmpeg >=4.3.2,<5.0a0
- pytorch * cuda

**Comment by ngam** [comment]
This would only work, in theory, because the ffmpeg 4.3.3 are marked broken. And it won't necessarily work correctly for pytorch.

**Comment by hmaarrfk** [comment]
In this PR your addressing the pin on pytorch.

We decided that we should pin to to the minor version to avoid unecessary rebuilds (in the long term).

The pytorch 1.10.0 has a run_exports to the exact version.
We just released 1.10.1 which has a run exports to the minor version.

I checked a few builds, and they seem to have found the 1.10.1 build, so the "pin" should be fixed.

We should submit a PR:
https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages
See for example this pinning patch
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/217/files

**Comment by ngam** [comment]
> We should submit a PR: https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages 
See for example this pinning patch https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/217/files

I've done both of these things before. I kinda think it's unnecessary for now, based on your comment that these patch releases are so similar it shouldn't be a problem. But I am happy to file the PRs in case you don't have time and you want them done

**Comment by hmaarrfk** [comment]
Did you submit a repo-data patch PR? I am having a hard time finding it.

The issue is that hte mgiration started with some packages being build with 1.10.0 (pinned at 1.10.0 during runtime) and others now are going to try to use 1.10.1 (like this package).

This will cause a conflict for users wishing to install both.

**Comment by ngam** [comment]
> Did you submit a repo-data patch PR? I am having a hard time finding it.
> 
> The issue is that hte mgiration started with some packages being build with 1.10.0 (pinned at 1.10.0 during runtime) and others now are going to try to use 1.10.1 (like this package).
> 
> This will cause a conflict for users wishing to install both.

I have not. Do you want me to do it or would you like to do it?

**Comment by ngam** [comment]
I think you should do it since you know the system better and this may be tricky for someone like me.

**Comment by hmaarrfk** [comment]
You can try to do it. I am not very familiar with the repo patching.

The idea is that we rewrite the archives, changing only the metadata.

I can review if you make the PR before others review.

**Comment by ngam** [comment]
Okay, I just checked around. My understanding is thus:

1. For a repopatch (or whatever it is actually called): we can only really change the build right before last night's (see screenshot for an example) with strings like linux-64/torchvision-0.11.2-py37cuda111h183f18d_0_cuda.tar.bz2. In this case, I would imagine we just change it from `pytorch 1.10.0.*` to simply pytorch*. 

2. However, I am afraid we might have a bigger problem: More recent cuda builds have a confusing constraint unlike anything else before, which is `pytorch * cuda` --- before it would be `pytorch *` AND `pytorch-cpu` or `pytorch-gpu`. I am not sure if `pytorch * cuda` actually works here. Could you check with the most recent variants (e.g. linux-64/torchvision-0.11.2-cuda112py38h5133249_2.tar.bz2
 see second screenshot)? I will get on a cuda-enabled setup soon and check for myself.

Screen Shot 2022-01-27 at 14 41 46

Screen Shot 2022-01-27 at 14 44 38

**Comment by ngam** [comment]
Okay, regarding 2. above, I think it resolves fine but I had to specify the exact hash (`cuda112py38h5133249_2`) to get it right (i.e. setting `cudatoolkit==11.2` didn't resolve it correctly) 

```
  + pytorch                1.10.1  cuda112py38h6425f36_0  conda-forge/linux-64      636 MB
  + readline                  8.1  h46c0cb4_0             conda-forge/linux-64      Cached
  + setuptools             60.5.0  py38h578d9bd_0         conda-forge/linux-64     1024 KB
  + sleef                   3.5.1  h9b69904_2             conda-forge/linux-64      Cached
  + sqlite                 3.37.0  h9cd32fc_0             conda-forge/linux-64      Cached
  + svt-av1                 0.9.0  h9c3ff4c_0             conda-forge/linux-64        3 MB
  + tbb                  2021.5.0  h4bd325d_0             conda-forge/linux-64      Cached
  + tk                     8.6.11  h27826a3_1             conda-forge/linux-64      Cached
  + torchvision            0.11.2  cuda112py38h5133249_2  conda-forge/linux-64        9 MB

```

**Comment by ngam** [comment]
With cudatoolkit==11.2 you get this (also just noticed ffmpeg... ugh)

```
  + cudatoolkit            11.2.2  he111cf0_10         conda-forge/linux-64     877 MB
  + ffmpeg                  4.4.1  h6987444_0          conda-forge/linux-64     Cached
  + pytorch                1.10.1  cpu_py39h5e9ed0b_0  conda-forge/linux-64      54 MB
  + torchvision            0.11.2  cpu_py39h5f8393d_2  conda-forge/linux-64      25 MB

```

**Comment by ngam** [comment]
Things seem to work fine... so let me think more about this

**Comment by hmaarrfk** [comment]
Hmmmm, you seem to be correct.

I'll have to look at how to better pin.

I don't really want to rely on the packages `pytorch-cpu` and `pytorch-gpu`.

They aren't compatible with upstream. It makes it difficult for people to use these recepies with upstream's packages.

**Comment by hmaarrfk** [comment]
For example, the cuda build has
```
{
  "arch": "x86_64",
  "build": "cuda112py39h14c6492_2",
  "build_number": 2,
  "depends": [
    "__glibc >=2.17",
    "__glibc >=2.17,<3.0.a0",
    "cudatoolkit >=11.2,<12",
    "cudnn >=8.2.1.32,<9.0a0",
    "ffmpeg >=4.3.2,<5.0a0",
    "jpeg >=9e,<10a",
    "libgcc-ng >=9.4.0",
    "libpng >=1.6.37,<1.7.0a0",
    "libstdcxx-ng >=9.4.0",
    "numpy >=1.19.5,<2.0a0",
    "pillow >=5.3.0,!=8.3.0,!=8.3.1",
    "python >=3.9,<3.10.0a0",
    "python_abi 3.9.* *_cp39",
    "pytorch * cuda*"
  ],
  "license": "BSD-3-Clause",
  "license_family": "BSD",
  "name": "torchvision",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1643258620122,
  "version": "0.11.2"
}
```

**Pull request closed without merging**
